apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-application-ingress
  namespace: {{ .Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.global.Frontend.BaseUrl }}
        backend:
          serviceName: {{ .Values.global.Frontend.ServiceName }}
          servicePort: {{ .Values.global.Frontend.Port }}
      - path: /api
        backend:
          serviceName: {{ .Values.global.Backend.ServiceName }}
          servicePort: {{ .Values.global.Backend.Port }}
      - path: /swagger
        backend:
          serviceName: {{ .Values.global.Backend.ServiceName }}
          servicePort: {{ .Values.global.Backend.Port }}